version: '3.0'

services:

  ng-app:
    build: ng-frontend
    volumes:
      - ./ng-frontend:/usr/src/app
      - ng-dist:/usr/src/app/dist/ng-frontend
      - /usr/src/app/node_modules

  express:
    build: express-server
    volumes:
      - ./express-server:/usr/src/app
      - ng-dist:/usr/src/app/ng-dist
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "ng-app"

volumes:
  ng-dist:
