version: '3.0'

services:

  database:
    image: 'mongo:4.2.7'
    restart: always
    environment:
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - /data/db
    ports:
      - "${MONGO_PORT}:27017"

  webserver:
    build: webserver
    restart: always
    environment:
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "${EXPRESS_PORT}:3000"
    links:
      - database
