version: '3.0'

services:

  ng-app:
    build: ng-frontend
    volumes:
      - ng-dist:/application/ng-frontend/dist/ng-frontend

  express:
    build: express-server
    volumes:
      - ng-dist:/application/ng-frontend/dist/ng-frontend
    ports:
      - "3000:3000"
    depends_on:
      - "ng-app"

volumes:
  ng-dist:
