apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: personal-website-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - nathanielwarner.net
    - www.nathanielwarner.net
    secretName: personal-website-tls
  rules:
  - host: nathanielwarner.net
    http:
      paths:
      - backend:
          serviceName: personal-website-svc
          servicePort: 80
