apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: personal-website-scaler
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: personal-website-server
  targetCPUUtilizationPercentage: 80
